### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [WJWH/HPi#4]
The documentation for the latest version of this package is missing on Hackage. It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by WJWH** [comment]
I would swear that this used to work :thinking: 
I will try to upload the documentation soon since I was planning to update the project to modern times anyway.

**Comment by WJWH** [comment]
Finally found the time for this, v0.7 now has properly working docs now.

**Comment by expipiplus1** [comment]
Thanks!
